spring:
  application:
    name: lab_9

  graphql:
    graphiql:
      path: /graphiql
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: MAE@#1020
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
